### PR TITLE
Advanced editor

### PR DESCRIPTION
**Pull request by LauraMakesArt**
+additional settings. Needs the Posting doc before this goes live. Proof
reading that one next.

### CODE REVIEW

**Comment by linc** [comment]
So this should be on Hold for now?

**Comment by LauraMakesArt** [comment]
It needs to be given a once over but it can go on hold until I have the posting doc up.

**Comment by Charrondev** [comment]
You should probably add a note in the alignment section that the markdown editor does not support it.

**Comment by LauraMakesArt** [comment]
Added a note to alignment on Adam's suggestion. @linc this should be good to go.

**Pull request merged**
